In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

sys.path.append('..')
os.chdir('..')

In [3]:
from datasets.pu_dataset import PUDataset

In [39]:
pu_dataset = PUDataset(artificial_damage=False, rdir='./data/dataset/PU/', max_per_class=1000)

In [40]:
sample_windows_pu = pu_dataset.inputs()[0:20]
sample_targets_pu = pu_dataset.targets()[0:20]

labels = pu_dataset.labels()

for i in range(len(sample_windows_pu)):
    print(f'Window {i}:')
    print(sample_windows_pu[i])
    print(f'Label: {labels[sample_targets_pu[i]]}')
    print('---')

Window 0:
tensor([[-0.0427,  0.0366, -0.0427,  ..., -0.0153, -0.0458, -0.1312]],
       dtype=torch.float64)
Label: OuterRace
---
Window 1:
tensor([[-0.3723, -0.3235, -0.0671,  ...,  0.1465,  0.2167,  0.1617]],
       dtype=torch.float64)
Label: InnerRace
---
Window 2:
tensor([[0.1495, 0.0336, 0.0366,  ..., 0.1587, 0.0732, 0.0092]],
       dtype=torch.float64)
Label: InnerRace
---
Window 3:
tensor([[-0.1038, -0.1251, -0.1099,  ..., -0.0336, -0.0214,  0.0153]],
       dtype=torch.float64)
Label: InnerRace
---
Window 4:
tensor([[-0.1770, -0.2197, -0.2502,  ..., -0.2075, -1.3641, -0.0397]],
       dtype=torch.float64)
Label: Healthy
---
Window 5:
tensor([[ 0.1312,  0.1587, -0.0488,  ..., -0.0092,  0.0214,  0.0183]],
       dtype=torch.float64)
Label: InnerRace
---
Window 6:
tensor([[ 0.0397, -0.0092,  0.0031,  ..., -0.1007,  0.0336, -0.0244]],
       dtype=torch.float64)
Label: InnerRace
---
Window 7:
tensor([[0.0519, 0.0732, 0.0153,  ..., 0.0244, 0.0641, 0.1923]],
       dtype=torch.floa

In [42]:
import json

## Export samples into csv
metadata_filepath = './samples/samples.json'

if not os.path.exists(metadata_filepath):
    os.makedirs(os.path.dirname(metadata_filepath), exist_ok=True)
    with open(metadata_filepath, 'w') as f:
        f.write('{}')
        
metadata = json.load(open(metadata_filepath, 'r'))

metadata["PU"] = []

for i in range(len(sample_windows_pu)):
    filename = f'pu_sample_window_{i+1}.csv'
    filepath = os.path.join('./samples/PU/', filename)
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    if os.path.exists(filepath):
        os.remove(filepath)
    
    metadata["PU"].append({
        "filename": filename,
        "label": labels[sample_targets_pu[i]],
        "sampling_rate": 64000,
    })
    with open(filepath, 'w') as f:
        f.write('row,ch1')
        for (row, value) in enumerate(sample_windows_pu[i][0].numpy()):
            f.write(f'\n{row},{value}')
    print(f'Exported sample window {i+1} to {filepath}')
    
with open(metadata_filepath, 'w') as f:
    json.dump(metadata, f, indent=4)

Exported sample window 1 to ./samples/PU/pu_sample_window_1.csv
Exported sample window 2 to ./samples/PU/pu_sample_window_2.csv
Exported sample window 3 to ./samples/PU/pu_sample_window_3.csv
Exported sample window 4 to ./samples/PU/pu_sample_window_4.csv
Exported sample window 5 to ./samples/PU/pu_sample_window_5.csv
Exported sample window 6 to ./samples/PU/pu_sample_window_6.csv
Exported sample window 7 to ./samples/PU/pu_sample_window_7.csv
Exported sample window 8 to ./samples/PU/pu_sample_window_8.csv
Exported sample window 9 to ./samples/PU/pu_sample_window_9.csv
Exported sample window 10 to ./samples/PU/pu_sample_window_10.csv
Exported sample window 11 to ./samples/PU/pu_sample_window_11.csv
Exported sample window 12 to ./samples/PU/pu_sample_window_12.csv
Exported sample window 13 to ./samples/PU/pu_sample_window_13.csv
Exported sample window 14 to ./samples/PU/pu_sample_window_14.csv
Exported sample window 15 to ./samples/PU/pu_sample_window_15.csv
Exported sample window 16 to

In [43]:
from datasets.cwru_dataset import CrwuDataset

cwru_dataset = CrwuDataset(rdir='./data/dataset/CWRU/')

Loading preprocessed data...


In [46]:
sample_windows_cwru = cwru_dataset.inputs()[0:20]
sample_targets_cwru = cwru_dataset.targets()[0:20]

labels_cwru = cwru_dataset.labels()

for i in range(len(sample_windows_cwru)):
    print(f'Window {i}:')
    print(sample_windows_cwru[i])
    print(f'Label: {labels_cwru[sample_targets_cwru[i]]}')
    print('---')

Window 0:
[[ 0.07049685  0.14732866  0.00357357 ...  0.09453725 -0.07780643
   0.03622303]]
Label: 0.021-Ball
---
Window 1:
[[ 0.21806916  0.06131926 -0.25096228 ...  0.04466966 -0.14700379
  -0.19573433]]
Label: 0.007-OuterRace
---
Window 2:
[[-0.15837425 -0.08089269  0.10233413 ...  0.08885202 -0.06237509
   0.06676084]]
Label: 0.021-Ball
---
Window 3:
[[-0.26192665 -0.11126806  0.04791836 ... -0.31187545 -0.16568383
  -0.08243583]]
Label: 0.021-OuterRace
---
Window 4:
[[-0.21717577  0.40446347  0.20515557 ... -0.08576575 -0.08316679
   0.23553094]]
Label: 0.021-Ball
---
Window 5:
[[-0.02795446 -0.10681108 -0.11411262 ...  0.09053908  0.12433477
   0.17648862]]
Label: Normal
---
Window 6:
[[ 0.01877538  0.01856677 -0.00396369 ... -0.02190462 -0.024408
  -0.03713354]]
Label: Normal
---
Window 7:
[[-0.06578623  0.12751158  0.07187754 ...  0.02192874  0.01380699
  -0.08609062]]
Label: 0.021-OuterRace
---
Window 8:
[[-0.00779689 -0.15512555 -0.00097461 ...  0.01283238 -0.10623257
  -0.05

In [52]:
import json

## Export samples into csv
metadata_filepath = './samples/samples.json'

if not os.path.exists(metadata_filepath):
    os.makedirs(os.path.dirname(metadata_filepath), exist_ok=True)
    with open(metadata_filepath, 'w') as f:
        f.write('{}')
        
metadata = json.load(open(metadata_filepath, 'r'))

metadata["CWRU"] = []

for i in range(len(sample_windows_cwru)):
    filename = f'CWRU_sample_window_{i+1}.csv'
    filepath = os.path.join('./samples/CWRU/', filename)
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    if os.path.exists(filepath):
        os.remove(filepath)
    
    metadata["CWRU"].append({
        "filename": filename,
        "label": labels_cwru[sample_targets_cwru[i]],
        "sampling_rate": 12000,
    })
    with open(filepath, 'w') as f:
        f.write('row,ch1')
        for (row, value) in enumerate(sample_windows_cwru[i][0]):
            f.write(f'\n{row},{value}')
    print(f'Exported sample window {i+1} to {filepath}')
    
with open(metadata_filepath, 'w') as f:
    json.dump(metadata, f, indent=4)

Exported sample window 1 to ./samples/CWRU/CWRU_sample_window_1.csv
Exported sample window 2 to ./samples/CWRU/CWRU_sample_window_2.csv
Exported sample window 3 to ./samples/CWRU/CWRU_sample_window_3.csv
Exported sample window 4 to ./samples/CWRU/CWRU_sample_window_4.csv
Exported sample window 5 to ./samples/CWRU/CWRU_sample_window_5.csv
Exported sample window 6 to ./samples/CWRU/CWRU_sample_window_6.csv
Exported sample window 7 to ./samples/CWRU/CWRU_sample_window_7.csv
Exported sample window 8 to ./samples/CWRU/CWRU_sample_window_8.csv
Exported sample window 9 to ./samples/CWRU/CWRU_sample_window_9.csv
Exported sample window 10 to ./samples/CWRU/CWRU_sample_window_10.csv
Exported sample window 11 to ./samples/CWRU/CWRU_sample_window_11.csv
Exported sample window 12 to ./samples/CWRU/CWRU_sample_window_12.csv
Exported sample window 13 to ./samples/CWRU/CWRU_sample_window_13.csv
Exported sample window 14 to ./samples/CWRU/CWRU_sample_window_14.csv
Exported sample window 15 to ./samples