In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

sys.path.append('..')
os.chdir('..')

In [3]:
from datasets.pu_dataset import PUDataset

In [4]:
pu_dataset = PUDataset(artificial_damage=False, rdir='./data/dataset/PU/', max_per_class=1000)

In [5]:
sample_windows_pu = pu_dataset.inputs()[0:20]
sample_targets_pu = pu_dataset.targets()[0:20]

labels = pu_dataset.labels()

for i in range(len(sample_windows_pu)):
    print(f'Window {i}:')
    print(sample_windows_pu[i])
    print(f'Label: {labels[sample_targets_pu[i]]}')
    print('---')

Window 0:
tensor([[ 0.1099, -0.0244, -0.2014,  ...,  0.0549,  0.0732,  0.0580]],
       dtype=torch.float64)
Label: InnerRace
---
Window 1:
tensor([[-0.1160,  0.0061, -0.0763,  ...,  0.1282, -0.0427, -0.0519]],
       dtype=torch.float64)
Label: Healthy
---
Window 2:
tensor([[ 0.3540,  0.0305, -0.2014,  ...,  0.0214,  0.0031,  0.0031]],
       dtype=torch.float64)
Label: Healthy
---
Window 3:
tensor([[ 0.1404,  0.1343,  0.1129,  ..., -0.0549, -0.1312, -0.1160]],
       dtype=torch.float64)
Label: OuterRace
---
Window 4:
tensor([[-0.0336, -0.1312, -0.0671,  ...,  0.1129,  0.0122,  0.3296]],
       dtype=torch.float64)
Label: Healthy
---
Window 5:
tensor([[ 0.2960, -0.0702, -0.5524,  ..., -0.0580,  0.2808,  0.0244]],
       dtype=torch.float64)
Label: Healthy
---
Window 6:
tensor([[-0.1740, -0.1526, -0.0305,  ...,  0.3693,  0.1953,  0.0183]],
       dtype=torch.float64)
Label: OuterRace
---
Window 7:
tensor([[-0.3418,  0.2258, -0.5981,  ...,  0.2228,  0.1190,  0.3021]],
       dtype=torc

In [6]:
import json

## Export samples into csv
metadata_filepath = './samples/samples.json'

if not os.path.exists(metadata_filepath):
    os.makedirs(os.path.dirname(metadata_filepath), exist_ok=True)
    with open(metadata_filepath, 'w') as f:
        f.write('{}')
        
metadata = json.load(open(metadata_filepath, 'r'))

metadata["PU"] = []

for i in range(len(sample_windows_pu)):
    fileLable = labels[sample_targets_pu[i]]
    filename = f'sample_{fileLable}_{i+1}.csv'
    filepath = os.path.join('./samples/PU/', filename)
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    if os.path.exists(filepath):
        os.remove(filepath)
    
    metadata["PU"].append({
        "filename": f"PU/{filename}",
        "label": fileLable,
        "sampling_rate": 64000,
    })
    with open(filepath, 'w') as f:
        f.write('row,ch1')
        for (row, value) in enumerate(sample_windows_pu[i][0].numpy()):
            f.write(f'\n{row},{value}')
    print(f'Exported sample window {i+1} to {filepath}')
    
with open(metadata_filepath, 'w') as f:
    json.dump(metadata, f, indent=4)

Exported sample window 1 to ./samples/PU/sample_InnerRace_1.csv
Exported sample window 2 to ./samples/PU/sample_Healthy_2.csv
Exported sample window 3 to ./samples/PU/sample_Healthy_3.csv
Exported sample window 4 to ./samples/PU/sample_OuterRace_4.csv
Exported sample window 5 to ./samples/PU/sample_Healthy_5.csv
Exported sample window 6 to ./samples/PU/sample_Healthy_6.csv
Exported sample window 7 to ./samples/PU/sample_OuterRace_7.csv
Exported sample window 8 to ./samples/PU/sample_InnerRace_8.csv
Exported sample window 9 to ./samples/PU/sample_Healthy_9.csv
Exported sample window 10 to ./samples/PU/sample_InnerRace_10.csv
Exported sample window 11 to ./samples/PU/sample_InnerRace_11.csv
Exported sample window 12 to ./samples/PU/sample_OuterRace_12.csv
Exported sample window 13 to ./samples/PU/sample_InnerRace_13.csv
Exported sample window 14 to ./samples/PU/sample_Healthy_14.csv
Exported sample window 15 to ./samples/PU/sample_InnerRace_15.csv
Exported sample window 16 to ./samples/P

In [8]:
from datasets.cwru_dataset import CrwuDataset

cwru_dataset = CrwuDataset(rdir='./data/dataset/CWRU/')

Loading preprocessed data...


In [9]:
sample_windows_cwru = cwru_dataset.inputs()[0:20]
sample_targets_cwru = cwru_dataset.targets()[0:20]

labels_cwru = cwru_dataset.labels()

for i in range(len(sample_windows_cwru)):
    print(f'Window {i}:')
    print(sample_windows_cwru[i])
    print(f'Label: {labels_cwru[sample_targets_cwru[i]]}')
    print('---')

Window 0:
[[ 0.07113785  0.06425354  0.06863446 ...  0.01794092 -0.02294769
  -0.00375508]]
Label: Normal
---
Window 1:
[[ 0.23195737  0.13725768 -0.04840567 ... -0.03508599  0.20353122
   0.09177585]]
Label: 0.007-OuterRace
---
Window 2:
[[-0.17591725 -0.01884248 -0.01331968 ... -0.08479114 -0.05945126
   0.16763305]]
Label: 0.007-OuterRace
---
Window 3:
[[-0.06919737 -0.06676084  0.04661888 ...  0.00146192  0.00406088
  -0.00178679]]
Label: 0.014-Ball
---
Window 4:
[[-0.12458774  0.09599916  0.09437481 ... -0.06026343  0.00422331
   0.03476112]]
Label: 0.007-Ball
---
Window 5:
[[-0.03859385 -0.03129231 -0.03817662 ... -0.07343262 -0.05632615
  -0.04672985]]
Label: Normal
---
Window 6:
[[-0.00779689 -0.15512555 -0.00097461 ...  0.01283238 -0.10623257
  -0.05360359]]
Label: 0.021-Ball
---
Window 7:
[[-0.09421238  0.21896255  0.10152196 ...  0.00341114  0.40982383
  -0.15642503]]
Label: 0.007-InnerRace
---
Window 8:
[[-0.06889617  0.11765533  0.13580299 ... -0.00742958  0.00978431
  -0.

In [10]:
import json

## Export samples into csv
metadata_filepath = './samples/samples.json'

if not os.path.exists(metadata_filepath):
    os.makedirs(os.path.dirname(metadata_filepath), exist_ok=True)
    with open(metadata_filepath, 'w') as f:
        f.write('{}')
        
metadata = json.load(open(metadata_filepath, 'r'))

metadata["CWRU"] = []

for i in range(len(sample_windows_cwru)):
    fileLable = labels_cwru[sample_targets_cwru[i]]
    filename = f'sample_{fileLable}_{i+1}.csv'
    filepath = os.path.join('./samples/CWRU/', filename)
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    if os.path.exists(filepath):
        os.remove(filepath)
    
    metadata["CWRU"].append({
        "filename": f"CWRU/{filename}",
        "label": fileLable,
        "sampling_rate": 12000,
    })
    with open(filepath, 'w') as f:
        f.write('row,ch1')
        for (row, value) in enumerate(sample_windows_cwru[i][0]):
            f.write(f'\n{row},{value}')
    print(f'Exported sample window {i+1} to {filepath}')
    
with open(metadata_filepath, 'w') as f:
    json.dump(metadata, f, indent=4)

Exported sample window 1 to ./samples/CWRU/sample_Normal_1.csv
Exported sample window 2 to ./samples/CWRU/sample_0.007-OuterRace_2.csv
Exported sample window 3 to ./samples/CWRU/sample_0.007-OuterRace_3.csv
Exported sample window 4 to ./samples/CWRU/sample_0.014-Ball_4.csv
Exported sample window 5 to ./samples/CWRU/sample_0.007-Ball_5.csv
Exported sample window 6 to ./samples/CWRU/sample_Normal_6.csv
Exported sample window 7 to ./samples/CWRU/sample_0.021-Ball_7.csv
Exported sample window 8 to ./samples/CWRU/sample_0.007-InnerRace_8.csv
Exported sample window 9 to ./samples/CWRU/sample_0.014-OuterRace_9.csv
Exported sample window 10 to ./samples/CWRU/sample_0.014-OuterRace_10.csv
Exported sample window 11 to ./samples/CWRU/sample_Normal_11.csv
Exported sample window 12 to ./samples/CWRU/sample_0.007-OuterRace_12.csv
Exported sample window 13 to ./samples/CWRU/sample_Normal_13.csv
Exported sample window 14 to ./samples/CWRU/sample_0.021-OuterRace_14.csv
Exported sample window 15 to ./sa