In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

sys.path.append('..')
os.chdir('..')

In [3]:
from datasets.pu_dataset import PUDataset

In [ ]:
pu_dataset = PUDataset(artificial_damage=False, rdir='./data/dataset/PU/', max_per_class=1000)

In [ ]:
sample_windows_pu = pu_dataset.inputs()[0:20]
sample_targets_pu = pu_dataset.targets()[0:20]

labels = pu_dataset.labels()

for i in range(len(sample_windows_pu)):
    print(f'Window {i}:')
    print(sample_windows_pu[i])
    print(f'Label: {labels[sample_targets_pu[i]]}')
    print('---')

Window 0:
tensor([[-0.1373, -0.9399, -0.4517,  ..., -0.1007, -0.1984, -0.1678]],
       dtype=torch.float64)
Label: OuterRace
---
Window 1:
tensor([[-0.2533, -0.1678, -0.2808,  ...,  0.1007, -0.0458, -0.1740]],
       dtype=torch.float64)
Label: Healthy
---
Window 2:
tensor([[ 0.1068,  0.1770, -0.0519,  ..., -0.0702, -0.3540, -0.0916]],
       dtype=torch.float64)
Label: Healthy
---
Window 3:
tensor([[ 0.0061,  0.0000, -0.0610,  ..., -0.0336,  0.0275,  0.1007]],
       dtype=torch.float64)
Label: Healthy
---
Window 4:
tensor([[0.0854, 0.0458, 0.0061,  ..., 0.1038, 0.0854, 0.0732]],
       dtype=torch.float64)
Label: InnerRace
---
Window 5:
tensor([[-0.0885, -0.1312, -0.1648,  ...,  0.2289,  0.3876,  0.3815]],
       dtype=torch.float64)
Label: OuterRace
---
Window 6:
tensor([[-0.0549, -0.0916, -0.1648,  ..., -0.0183,  0.0549,  0.1556]],
       dtype=torch.float64)
Label: Healthy
---
Window 7:
tensor([[-0.1038, -0.0946, -0.0702,  ..., -0.1678, -0.0244,  0.1007]],
       dtype=torch.floa

In [ ]:
import json

## Export samples into csv
metadata_filepath = './samples/samples.json'

if not os.path.exists(metadata_filepath):
    os.makedirs(os.path.dirname(metadata_filepath), exist_ok=True)
    with open(metadata_filepath, 'w') as f:
        f.write('{}')
        
metadata = json.load(open(metadata_filepath, 'r'))

metadata["PU"] = []

for i in range(len(sample_windows_pu)):
    filename = f'pu_sample_window_{i+1}.csv'
    filepath = os.path.join('./samples/PU/', filename)
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    if os.path.exists(filepath):
        os.remove(filepath)
    
    metadata["PU"].append({
        "filename": filename,
        "label": labels[sample_targets_pu[i]],
        "sampling_rate": 64000,
    })
    with open(filepath, 'w') as f:
        f.write('row,ch1')
        for (row, value) in enumerate(sample_windows_pu[i][0].numpy()):
            f.write(f'\n{row},{value}')
    print(f'Exported sample window {i+1} to {filepath}')
    
with open(metadata_filepath, 'w') as f:
    json.dump(metadata, f, indent=4)

Exported sample window 1 to ./samples/PU/pu_sample_window_1.csv
Exported sample window 2 to ./samples/PU/pu_sample_window_2.csv
Exported sample window 3 to ./samples/PU/pu_sample_window_3.csv
Exported sample window 4 to ./samples/PU/pu_sample_window_4.csv
Exported sample window 5 to ./samples/PU/pu_sample_window_5.csv
Exported sample window 6 to ./samples/PU/pu_sample_window_6.csv
Exported sample window 7 to ./samples/PU/pu_sample_window_7.csv
Exported sample window 8 to ./samples/PU/pu_sample_window_8.csv
Exported sample window 9 to ./samples/PU/pu_sample_window_9.csv
Exported sample window 10 to ./samples/PU/pu_sample_window_10.csv
Exported sample window 11 to ./samples/PU/pu_sample_window_11.csv
Exported sample window 12 to ./samples/PU/pu_sample_window_12.csv
Exported sample window 13 to ./samples/PU/pu_sample_window_13.csv
Exported sample window 14 to ./samples/PU/pu_sample_window_14.csv
Exported sample window 15 to ./samples/PU/pu_sample_window_15.csv
Exported sample window 16 to

In [31]:
from datasets.cwru_dataset import CrwuDataset

cwru_dataset = CrwuDataset(rdir='./data/dataset/CWRU/')

Loading preprocessed data...


In [38]:
sample_windows_cwru = cwru_dataset.inputs()[0:20]
sample_targets_cwru = cwru_dataset.targets()[0:20]

labels = cwru_dataset.labels()

for i in range(len(sample_windows_cwru)):
    print(f'Window {i}:')
    print(sample_windows_cwru[i])
    print(f'Label: {labels[sample_targets_cwru[i]]}')
    print('---')

Window 0:
[[-1.25602964  0.85562705  0.92628633 ... -0.53197505 -0.54659421
   0.03736008]]
Label: 0.021-OuterRace
---
Window 1:
[[ 0.05858407 -0.02931234  0.04514587 ... -0.03126108  0.21955832
   0.04189796]]
Label: 0.014-OuterRace
---
Window 2:
[[ 0.02419938  0.01209969  0.01835815 ... -0.14164985 -0.13393108
  -0.07468431]]
Label: Normal
---
Window 3:
[[-0.28815992 -0.07407042 -0.39358032 ...  0.12816132  0.22643457
   0.05555281]]
Label: 0.007-InnerRace
---
Window 4:
[[ 0.10249657  0.04889297  0.07065928 ... -0.06984711 -0.00016244
   0.03459868]]
Label: 0.014-Ball
---
Window 5:
[[-0.40560052 -0.24836331  0.49818854 ... -0.93968723  0.47674711
   0.53294966]]
Label: 0.007-OuterRace
---
Window 6:
[[ 0.03102511  0.10704475 -0.02014196 ...  0.33916455  0.07504503
  -0.15106467]]
Label: 0.007-OuterRace
---
Window 7:
[[ 0.02712     0.05090215  0.08532369 ... -0.05570031 -0.06404492
  -0.05069354]]
Label: Normal
---
Window 8:
[[ 0.04426357  0.08974541 -0.01258872 ...  0.12223244 -0.1323

In [ ]:
import json

## Export samples into csv
metadata_filepath = './samples/samples.json'

if not os.path.exists(metadata_filepath):
    os.makedirs(os.path.dirname(metadata_filepath), exist_ok=True)
    with open(metadata_filepath, 'w') as f:
        f.write('{}')
        
metadata = json.load(open(metadata_filepath, 'r'))

metadata["CWRU"] = []

for i in range(len(cwru_dataset)):
    filename = f'CWRU_sample_window_{i+1}.csv'
    filepath = os.path.join('./samples/CWRU/', filename)
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    if os.path.exists(filepath):
        os.remove(filepath)
    
    metadata["CWRU"].append({
        "filename": filename,
        "label": labels[sample_targets_cwru[i]],
        "sampling_rate": 12000,
    })
    with open(filepath, 'w') as f:
        f.write('row,ch1')
        for (row, value) in enumerate(sample_windows_cwru[i][0]):
            f.write(f'\n{row},{value}')
    print(f'Exported sample window {i+1} to {filepath}')
    
with open(metadata_filepath, 'w') as f:
    json.dump(metadata, f, indent=4)

Exported sample window 1 to ./samples/CWRU/CWRU_sample_window_1.csv
Exported sample window 2 to ./samples/CWRU/CWRU_sample_window_2.csv
Exported sample window 3 to ./samples/CWRU/CWRU_sample_window_3.csv
Exported sample window 4 to ./samples/CWRU/CWRU_sample_window_4.csv
Exported sample window 5 to ./samples/CWRU/CWRU_sample_window_5.csv
Exported sample window 6 to ./samples/CWRU/CWRU_sample_window_6.csv
Exported sample window 7 to ./samples/CWRU/CWRU_sample_window_7.csv
Exported sample window 8 to ./samples/CWRU/CWRU_sample_window_8.csv
Exported sample window 9 to ./samples/CWRU/CWRU_sample_window_9.csv
Exported sample window 10 to ./samples/CWRU/CWRU_sample_window_10.csv
Exported sample window 11 to ./samples/CWRU/CWRU_sample_window_11.csv
Exported sample window 12 to ./samples/CWRU/CWRU_sample_window_12.csv
Exported sample window 13 to ./samples/CWRU/CWRU_sample_window_13.csv
Exported sample window 14 to ./samples/CWRU/CWRU_sample_window_14.csv
Exported sample window 15 to ./samples

IndexError: index 20 is out of bounds for axis 0 with size 20